name: app-release

on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  app-build:
    runs-on: ${{ matrix.os }}
    name: Build NodeJS ${{ matrix.node_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: [ '18' ]
        os: [ windows-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # 版本号
      - name: Get Version Name
        uses: actions/github-script@v3
        id: get-version-no-v
        with:
          script: |
            const str=process.env.GITHUB_REF;
            return str.substring(str.indexOf("v")+1);
          result-encoding: string
      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{steps.get-version-no-v.outputs.result}}
      - name: Setup NodeJS ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Cache dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Build Windows
        run: npm run build:win
      # 创建release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GitHub 会自动创建 GITHUB_TOKEN 密码以在工作流程中使用。
          #您可以使用 GITHUB_TOKEN 在工作流程运行中进行身份验证。
          #当您启用 GitHub Actions 时，GitHub 在您的仓库中安装 GitHub 应用程序。
          #GITHUB_TOKEN 密码是一种 GitHub 应用程序 安装访问令牌。
          #您可以使用安装访问令牌代表仓库中安装的 GitHub 应用程序 进行身份验证。
          #令牌的权限仅限于包含您的工作流程的仓库。 更多信息请参阅“GITHUB_TOKEN 的权限”。
          #在每个作业开始之前， GitHub 将为作业提取安装访问令牌。 令牌在作业完成后过期。
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      # 上传至release的资源
      - name: Upload Release Windows Portable Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传网址，无需改动
          asset_path: release/MagicBox_v${{steps.get-version-no-v.outputs.result}}_x64_Portable.exe # 上传路径
          asset_name: MagicBox_v${{steps.get-version-no-v.outputs.result}}_windows_${{steps.get-version.outputs.result}}_x64_Portable.exe # 资源名
          asset_content_type: application/vnd.microsoft.portable-executable #资源类型
      # 上传至release的资源
      - name: Upload Release Windows zip Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传网址，无需改动
          asset_path: release/MagicBox_v${{steps.get-version-no-v.outputs.result}}_x64.zip # 上传路径
          asset_name: MagicBox_v${{steps.get-version-no-v.outputs.result}}_windows_${{steps.get-version.outputs.result}}_x64.zip # 资源名
          asset_content_type: application/zip #资源类型
